package git

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// Hook represents a Git hook
type Hook struct {
	Name    string
	Path    string
	Content string
	Enabled bool
}

// InstallCommitMsgHook installs the commit-msg hook
func (r *Repository) InstallCommitMsgHook(force bool) error {
	hooksDir, err := r.GetHooksDir()
	if err != nil {
		return fmt.Errorf("failed to get hooks directory: %v", err)
	}

	// Create hooks directory if it doesn't exist
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %v", err)
	}

	hookPath := filepath.Join(hooksDir, "commit-msg")

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil && !force {
		return fmt.Errorf("hook already exists at %s. Use --force to overwrite", hookPath)
	}

	// Create backup if exists
	if _, err := os.Stat(hookPath); err == nil {
		backupPath := hookPath + ".backup"
		if err := copyFile(hookPath, backupPath); err != nil {
			return fmt.Errorf("failed to backup existing hook: %v", err)
		}
		fmt.Printf("Backed up existing hook to: %s\n", backupPath)
	}

	// Generate hook content
	hookContent := generateHookContent()

	// Write hook file
	if err := os.WriteFile(hookPath, []byte(hookContent), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %v", err)
	}

	fmt.Printf("✓ Installed commit-msg hook at: %s\n", hookPath)
	return nil
}

// UninstallCommitMsgHook removes the commit-msg hook
func (r *Repository) UninstallCommitMsgHook() error {
	hooksDir, err := r.GetHooksDir()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(hooksDir, "commit-msg")

	// Check if our hook is installed
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("no hook found at %s", hookPath)
	}

	if !strings.Contains(string(content), "commit-lint") {
		return fmt.Errorf("hook at %s is not a commit-lint hook", hookPath)
	}

	// Restore backup if exists
	backupPath := hookPath + ".backup"
	if _, err := os.Stat(backupPath); err == nil {
		if err := copyFile(backupPath, hookPath); err != nil {
			return fmt.Errorf("failed to restore backup: %v", err)
		}
		fmt.Printf("✓ Restored original hook from backup\n")
		// Remove backup
		os.Remove(backupPath)
	} else {
		// No backup, just remove our hook
		if err := os.Remove(hookPath); err != nil {
			return fmt.Errorf("failed to remove hook: %v", err)
		}
		fmt.Printf("✓ Removed commit-lint hook\n")
	}

	return nil
}

// IsHookInstalled checks if commit-lint hook is installed
func (r *Repository) IsHookInstalled() (bool, error) {
	hooksDir, err := r.GetHooksDir()
	if err != nil {
		return false, err
	}

	hookPath := filepath.Join(hooksDir, "commit-msg")
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return false, nil // File doesn't exist
	}

	return strings.Contains(string(content), "commit-lint"), nil
}

// generateHookContent creates the hook script
func generateHookContent() string {
	return `#!/bin/sh
#
# commit-msg hook generated by commit-lint
# Validates commit messages against Conventional Commits
#

# Get the commit message file path
COMMIT_MSG_FILE="$1"

# Read the commit message
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Use commit-lint to validate
if command -v commit-lint >/dev/null 2>&1; then
    commit-lint "$COMMIT_MSG"
    EXIT_CODE=$?
    
    if [ $EXIT_CODE -ne 0 ]; then
        echo ""
        echo "❌ Commit message validation failed."
        echo "   Please fix the message and try again."
        echo "   To bypass (not recommended): git commit --no-verify"
        exit 1
    fi
else
    echo "⚠️  commit-lint not found in PATH"
    echo "   Install it with: go install github.com/yourusername/commit-linter/cmd/commit-lint@latest"
fi

exit 0
`
}

// Helper function to copy files
func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()

	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()

	_, err = io.Copy(out, in)
	if err != nil {
		return err
	}

	// Copy permissions
	stat, err := os.Stat(src)
	if err == nil {
		os.Chmod(dst, stat.Mode())
	}

	return nil
}
